services:
  - type: web
    name: youtube_audio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "pythone rezka_bot.py"
    runtime: python
    pythonVersion: 3.13